spring:
  application:
    name: project-collaboration-platform

server:
  port: 8080

app:
  jwt:
    secret: portfolio-demo-secret-change-me
    expire-minutes: 240

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
